boot.o: boot.S multiboot.h x86_desc.h types.h PeachOS_IDT.h
PeachOS_Interrupt.o: PeachOS_Interrupt.S x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
i8259.o: i8259.c i8259.h types.h lib.h PeachOS_Terminal.h \
  PeachOS_Keyboard.h x86_desc.h PeachOS_Interrupt.h PeachOS_RTC.h \
  PeachOS_FileSys.h PeachOS_SystemCalls.h PeachOS_Scheduling.h \
  PeachOS_PAGING.h PeachOS_IDT.h PeachOS_SystemCall_Test.h debug.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h \
  PeachOS_Terminal.h i8259.h PeachOS_Keyboard.h PeachOS_Interrupt.h \
  PeachOS_RTC.h PeachOS_FileSys.h PeachOS_SystemCalls.h \
  PeachOS_Scheduling.h PeachOS_PAGING.h PeachOS_IDT.h \
  PeachOS_SystemCall_Test.h debug.h PeachOS_PIT.h
lib.o: lib.c lib.h types.h PeachOS_Terminal.h i8259.h PeachOS_Keyboard.h \
  x86_desc.h PeachOS_Interrupt.h PeachOS_RTC.h PeachOS_FileSys.h \
  PeachOS_SystemCalls.h PeachOS_Scheduling.h PeachOS_PAGING.h \
  PeachOS_IDT.h PeachOS_SystemCall_Test.h debug.h
PeachOS_FileSys.o: PeachOS_FileSys.c PeachOS_FileSys.h types.h lib.h \
  PeachOS_Terminal.h i8259.h PeachOS_Keyboard.h x86_desc.h \
  PeachOS_Interrupt.h PeachOS_RTC.h PeachOS_SystemCalls.h \
  PeachOS_Scheduling.h PeachOS_PAGING.h PeachOS_IDT.h \
  PeachOS_SystemCall_Test.h debug.h
PeachOS_IDT.o: PeachOS_IDT.c lib.h types.h PeachOS_Terminal.h i8259.h \
  PeachOS_Keyboard.h x86_desc.h PeachOS_Interrupt.h PeachOS_RTC.h \
  PeachOS_FileSys.h PeachOS_SystemCalls.h PeachOS_Scheduling.h \
  PeachOS_PAGING.h PeachOS_IDT.h PeachOS_SystemCall_Test.h debug.h
PeachOS_Keyboard.o: PeachOS_Keyboard.c PeachOS_Keyboard.h lib.h types.h \
  PeachOS_Terminal.h i8259.h PeachOS_IDT.h PeachOS_Interrupt.h \
  PeachOS_SystemCall_Test.h x86_desc.h debug.h PeachOS_PAGING.h \
  PeachOS_RTC.h PeachOS_FileSys.h PeachOS_SystemCalls.h \
  PeachOS_Scheduling.h
PeachOS_PAGING.o: PeachOS_PAGING.c types.h PeachOS_PAGING.h
PeachOS_PIT.o: PeachOS_PIT.c PeachOS_PIT.h types.h lib.h \
  PeachOS_Terminal.h i8259.h PeachOS_Keyboard.h x86_desc.h \
  PeachOS_Interrupt.h PeachOS_RTC.h PeachOS_FileSys.h \
  PeachOS_SystemCalls.h PeachOS_Scheduling.h PeachOS_PAGING.h \
  PeachOS_IDT.h PeachOS_SystemCall_Test.h debug.h
PeachOS_RTC.o: PeachOS_RTC.c PeachOS_RTC.h types.h lib.h \
  PeachOS_Terminal.h i8259.h PeachOS_Keyboard.h x86_desc.h \
  PeachOS_Interrupt.h PeachOS_FileSys.h PeachOS_SystemCalls.h \
  PeachOS_Scheduling.h PeachOS_PAGING.h PeachOS_IDT.h \
  PeachOS_SystemCall_Test.h debug.h
PeachOS_Scheduling.o: PeachOS_Scheduling.c PeachOS_Scheduling.h \
  PeachOS_Terminal.h lib.h types.h i8259.h PeachOS_Keyboard.h x86_desc.h \
  PeachOS_Interrupt.h PeachOS_RTC.h PeachOS_FileSys.h \
  PeachOS_SystemCalls.h PeachOS_IDT.h PeachOS_SystemCall_Test.h debug.h \
  PeachOS_PAGING.h
PeachOS_SystemCalls.o: PeachOS_SystemCalls.c lib.h types.h \
  PeachOS_Terminal.h i8259.h PeachOS_Keyboard.h x86_desc.h \
  PeachOS_Interrupt.h PeachOS_RTC.h PeachOS_FileSys.h \
  PeachOS_SystemCalls.h PeachOS_Scheduling.h PeachOS_PAGING.h \
  PeachOS_IDT.h PeachOS_SystemCall_Test.h debug.h
PeachOS_SystemCall_Test.o: PeachOS_SystemCall_Test.c \
  PeachOS_SystemCall_Test.h types.h x86_desc.h lib.h PeachOS_Terminal.h \
  i8259.h PeachOS_Keyboard.h PeachOS_Interrupt.h PeachOS_RTC.h \
  PeachOS_FileSys.h PeachOS_SystemCalls.h PeachOS_Scheduling.h \
  PeachOS_PAGING.h PeachOS_IDT.h debug.h
PeachOS_Terminal.o: PeachOS_Terminal.c PeachOS_Terminal.h lib.h types.h \
  PeachOS_Scheduling.h PeachOS_PAGING.h PeachOS_SystemCalls.h x86_desc.h \
  i8259.h PeachOS_Keyboard.h PeachOS_Interrupt.h PeachOS_RTC.h \
  PeachOS_FileSys.h PeachOS_IDT.h PeachOS_SystemCall_Test.h debug.h
